//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageTool.WordAddin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localTemplates.json")]
        public string localSnippetsFileName {
            get {
                return ((string)(this["localSnippetsFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://landlord.pronetcre.com/ajax/language_library_ajax.php?action=get_data_for" +
            "_onlyoffice_plugin&token=")]
        public string snippetsEndpoint {
            get {
                return ((string)(this["snippetsEndpoint"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://landlord.pronetcre.com/ajax/language_library_ajax.php?action=check_for_up" +
            "date_onlyoffice_plugin&token=")]
        public string checkForUpdatesEndpoint {
            get {
                return ((string)(this["checkForUpdatesEndpoint"]));
            }
            set {
                this["checkForUpdatesEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://landlord.pronetcre.com/ajax/language_library_ajax.php?action=validate_tok" +
            "en_onlyoffice_plugin&token=")]
        public string tokenValidityEndpoint {
            get {
                return ((string)(this["tokenValidityEndpoint"]));
            }
            set {
                this["tokenValidityEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isTokenValid {
            get {
                return ((bool)(this["isTokenValid"]));
            }
            set {
                this["isTokenValid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("userToken.json")]
        public string localTokenFileName {
            get {
                return ((string)(this["localTokenFileName"]));
            }
            set {
                this["localTokenFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int retriesLeft {
            get {
                return ((int)(this["retriesLeft"]));
            }
            set {
                this["retriesLeft"] = value;
            }
        }
    }
}
